overrides:
  - files:
      - "*.js"
      - "*.ts"
    options:
      arrowParens: always
      singleQuote: true
      trailingComma: es5
      useTabs: true
  - files:
      - "*.html"
    options:
      useTabs: true
